### ISSUE TITLE
Different font sizes?

### ISSUE THREAD

**Issue by callodacity** [ruddfawcett/Notepad#14]
Would it be possible to adjust the size of different tokens?

For example, a level 1 header `# Heading` could be a larger font size than standard text.

Something like CodeMirror's implementation: http://codemirror.net/demo/variableheight.html

**Comment by ruddfawcett** [comment]
Yes! What you're looking for is to define `"size'` for an [element in your stylesheet](https://github.com/ruddfawcett/Notepad/blob/master/Notepad/Theme.swift#L121-L129).

You can either edit an existing stylesheet, or create a new one to do this!

**Comment by callodacity** [comment]
Legendary 👍 thanks for that!
