### ISSUE TITLE
... 

### ISSUE THREAD

**Issue by Rdxer** [ruddfawcett/Notepad#16]
<img width="746" alt="qq20170719-154010 2x" src="https://user-images.githubusercontent.com/8586111/28356071-3d9e162e-6c99-11e7-9088-0cc46847a411.png">

**Comment by Rdxer** [comment]
Create project, then...

**Comment by ruddfawcett** [comment]
Sorry, what's your question?

**Comment by Rdxer** [comment]
Using the GIT submodule, with pod, there are no errors. The tag version is not set?

**Comment by Rdxer** [comment]
My English is poor. 😂

**Comment by ruddfawcett** [comment]
没关系我们可以用中文吗？你有什么问题？我觉得如果你用第最新的Pod,可能没有问题吗。但是我会看一看！

对不起，我写中文写得不好。
