### ISSUE TITLE
make a Type for built-in themes

### ISSUE THREAD

**Issue by DivineDominion** [ruddfawcett/Notepad#17]
While working with the library, it took me a second to notice that `Theme(_:)` doesn't load a file from my app target but only from the framework target -- so it's supposed to work with built-in themes only.

Making this clear with a named parameter, like `Theme(builtInThemeName: String)`, looks awful. But I had an idea:

```swift
// A different name may be desirable
enum BuiltInTheme: String {
    case oneDark: "themes/one-dark"
    // ...
}
```

Then resolving the bundle path can be moved into that type as well.

The initializer changes to `Theme(_ builtIn: BuiltInTheme)` and can be called with `Theme(.oneDark)`. Upside: client apps can know which themes are built-in without looking at the source, because the enum cases are easily discoverable in Xcode.

Also, this frees up the string-based initializer to work with `Bundle.main` so that client apps can call `Theme("custom")` to load a resource from the app bundle.

**Comment by ruddfawcett** [comment]
This is definitely confusing as it stands, and I like the idea of using an enum. I'm wondering, however, if you think that the `BuiltInTheme` should be standalone or on `Theme` (e.g. `Theme.builtIn.XY`)?

**Comment by DivineDominion** [comment]
Good point. Maybe something like this would also work: `Theme.BuiltIn.oneDark.rawValue` where `Theme.BuiltIn` is an enum (I don't want to ditch the enum in favor of static properties just yet because they are the best fit for a list of options); `Theme` then has to become `RawRepresentable` or similar in order to make `struct Theme { enum BuiltIn: Theme { ... } }` possible 🤔

**Comment by ruddfawcett** [comment]
Yeah — I agree that it would be most flexible for `Theme.BuiltIn` to be an enum, yet perhaps `BuiltIn` is a `String` enum rather than a `Theme`? That would eliminate the need for `Theme` to be `RawRepresentable`, no?

Looking at `Theme` specifically, it definitely needs work in general. In hindsight, I'm not sure why I put all of the JSON parsing functions in the struct.

**Comment by thbonk** [comment]
I created a pull request for that: https://github.com/ruddfawcett/Notepad/pull/55
