### ISSUE TITLE
Features and bugs.

### ISSUE THREAD

**Issue by WildDylan** [ruddfawcett/Notepad#2]
![image](https://cloud.githubusercontent.com/assets/2519544/20293337/6d3d0e9c-ab30-11e6-8974-26d195656a8f.png)

code block is not support. like use
```java 
public ...
```
regex with error.
more element type support. h4, h5, h6, line, steps. 
how about show the image. 
how about support html element.

**Comment by ruddfawcett** [comment]
Hi, you are more than welcome to add the features you requested (multiline code, h4, h5, h6), but I don't have any plans to support HTML or inline images. 

Thank you for the bug report, though. I will look into fixing that at one point.

**Comment by WildDylan** [comment]
I used 2 indent in my editor....
