### ISSUE TITLE
fix bold + italic: consider adding traits to a base font instead of requiring font names

### ISSUE THREAD

**Issue by DivineDominion** [ruddfawcett/Notepad#20]
I found that to get a bold & italic font, coming up with a `XYZ-BoldItalic` name doesn't work, but adding a font trait via `NSFontManager` does work. 

Instead of requiring `font` names in the theme files, my suggestion is to add another property, maybe even call it "traits", where you can specify "bold", "italic", or both. 

* If the current style scope has a font setting, it adds the traits to the font name -- thus making a setting like `"font": "Menlo-Bold", traits: [ "bold" ]` redundant.
* If the current style's scope has no font name set, the style will use the base (body) font and add the traits. 
* If no style ever did set a custom font, it falls back to the current system font.

What do you think?

**Comment by ruddfawcett** [comment]
Sounds great!

**Comment by funkenstrahlen** [comment]
This is a great idea in I'd love to see this too. Maybe I will find time to submit a PR.

**Comment by funkenstrahlen** [comment]
I tried to implement this because I need it in my current project too. Do you want to take a look and maybe merge? https://github.com/ruddfawcett/Notepad/pull/47

**Comment by ruddfawcett** [comment]
Hey thanks so much @funkenstrahlen — I'll take a look!
