### ISSUE TITLE
swift 4?

### ISSUE THREAD

**Issue by kobble-git** [ruddfawcett/Notepad#23]
Tried using Notepad with swift 4 and Xcode 9, but get a few errors. Some have simple fixes, others not so much. Any plans for swift 4?

**Comment by ruddfawcett** [comment]
Hey, thanks for the issue! I would love for Notepad to support Swift 4. Unfortunately I haven't been able to work on Notepad for a little bit, but I'll try to get these issues fixed as soon as I download all of the latest Apple development tools.

**Comment by kobble-git** [comment]
I made the changes. I'm running them locally, and they seem to be working. I created a pull request.

**Comment by ruddfawcett** [comment]
@kobble-git Thanks, I'll check them out!
