### ISSUE TITLE
Change text programmatically

### ISSUE THREAD

**Issue by kobble-git** [ruddfawcett/Notepad#25]
If I set the text property to a string after initialization, it loads, but the text is truncated. Is this the right way to set text in Notepad?

**Comment by DivineDominion** [comment]
Just tried both macOS and iOS sample codes with 

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) { editor.text = text }
```

To see what happens when the view is already loaded and you reset the text. Works fine. Can you provide more context information?

**Comment by kobble-git** [comment]
The problem was the string length calculation in Storage.replaceCharacters. I submitted a pull request with the fix. For certain strings, str.characters.count does not return the correct length, NSString.length does.

**Comment by DivineDominion** [comment]
Of course it doesn't, good catch, thanks! So it's solved now?

**Comment by kobble-git** [comment]
Yes, I think so.
