### ISSUE TITLE
Suggestion box is too big

### ISSUE THREAD

**Issue by danielmekis** [ruddfawcett/Notepad#29]
I have a problem when my TextView starts with a `#Title`
<img width="348" alt="screen shot 2017-11-22 at 9 14 27" src="https://user-images.githubusercontent.com/33416593/33116633-d4974288-cf65-11e7-89e4-bbb490dbcd7b.png">

As you can see the cursor and the suggestion box is too big, I guess it uses the title's size value. Is there any way to fix it?

**Comment by ruddfawcett** [comment]
Hm. I'm not sure if this is a Notepad problem — at least, I've never seen this behavior.  Can you post any relevant code?

**Comment by danielmekis** [comment]
@ruddfawcett It happens when you start the whole text with a #Title. It has bigger font so I guess this causes the problem. If I start normally there is no problem.

**Comment by ruddfawcett** [comment]
So sorry for the delay here, I was in the midst of finals and lost track of GitHub issues. I'll investigate further and get back to you. Your assessment about the bug sounds accurate, though.

**Comment by ruddfawcett** [comment]
Hi, I'm so sorry — I  know this is a very old issue. I just tried to replicate it and was unable to do so. Please let me know if you are still experiencing any problems.
