### ISSUE TITLE
Align text in the centre

### ISSUE THREAD

**Issue by danielmekis** [ruddfawcett/Notepad#30]
Is there any way to align text centre?
I set `.textAlignment` to centre, but when I type down one letter, it jumps back to left.

**Comment by wakaryry** [comment]
You could custome your markdown previewer or viewer or render to make a center style. No need to make center in editor.

**Comment by ruddfawcett** [comment]
Hi, sorry for the delay. You can fiddle with the text alignment [either here](https://github.com/ruddfawcett/Notepad/blob/master/Notepad/Theme.swift#L81) or [here](https://github.com/ruddfawcett/Notepad/blob/master/Notepad/Theme.swift#L70). Please reopen this issue if you are still having trouble or need more help. You may also try [stackoverflow.com](https://stackoverflow.com/) for general questions or help.
