### ISSUE TITLE
Swift 4 support (on CocoaPods)?

### ISSUE THREAD

**Issue by TomasPangzi** [ruddfawcett/Notepad#34]
as the title, swift 4 with cocoapods

**Comment by ruddfawcett** [comment]
Library should be up to Swift 4 if you include from the GitHub source in your Podfile, but I do need to update it on CocoaPods.

**Comment by funkenstrahlen** [comment]
Works fine even with Swift 5 when using the version from Github.

**Comment by ruddfawcett** [comment]
Closed via #50, #49.
