### ISSUE TITLE
3 spaces make it not working

### ISSUE THREAD

**Issue by TomasPangzi** [ruddfawcett/Notepad#35]
text like *write and edit Markdown* , have 3 or more spaces can make program not working
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8348504/43264531-02d11a28-9119-11e8-9885-3de520ec220d.png">

**Comment by TomasPangzi** [comment]
and can only dark theme work, in branch swift-4

**Comment by ruddfawcett** [comment]
Can you elaborate on your problem and open a new issue for the second concern?

**Comment by ruddfawcett** [comment]
@TomasPangzi I can't seem to reproduce this on `master` (which `swift-4` was merged into). Please let me know if you are still experiencing a problem.
