### ISSUE TITLE
Internal Protection Level

### ISSUE THREAD

**Issue by curtisbacon** [ruddfawcett/Notepad#37]
> initializer is inaccessible due to 'internal' protection level

I think the Notepad's convenience initializer needs to be made public in order to access it from outside the framework.

**Comment by curtisbacon** [comment]
That is correct

**Comment by curtisbacon** [comment]
Also, you know if the commit [319710a](https://github.com/ruddfawcett/Notepad/commit/319710aff2db1a7cfc6d2de76fae1d77c5337298) regarding the cocoapods theme loading was pushed to the master branch? Or is it part of a different branch? Thanks a lot btw.

**Comment by ruddfawcett** [comment]
@curtisbacon It should be on master. Let me check out what's happening with this one sec.

**Comment by ruddfawcett** [comment]
Hey, @curtisbacon, can you send me some more details about your usage?

**Comment by curtisbacon** [comment]
Hi @ruddfawcett sorry for getting back late. 
* Working with Swift 3.3
* Running cocoapods 1.5.3 (the Latest version I believe)
* Using Notepad (0.2.4) 

` var editor: UITextView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        editor = Notepad(self.boundsView.bounds, themeFile: "one-dark")
        editor.backgroundColor = Constants.kDarkGrayBackgroundColor
        editor.layer.borderWidth = 1
        editor.layer.borderColor = Constants.userTypeBasedColor().cgColor

        self.boundsView.addSubview(editor)
}
`
This usage promotes the error 

> initializer is inaccessible due to 'internal' protection level

Also, I cannot access the themeFile as requested in commit 319710a regarding the cocoapods theme loading. So the initialisation of the *one-dark* theme does not work.

I have temporarily fixed these issues by editing the pod files directly, but obviously, this isn't a long-term solution.

**Comment by curtisbacon** [comment]
It doesn't look like the latest release 0.2.4 contains the changes mentioned in the above commit - *Theme.swift* still contains: 
`        if let path = Bundle(for: object_getClass(self)).path(forResource: "Notepad.framework/themes/\(name)", ofType: "json") {
            if let data = convertFile(path) {
                configure(data)
            }
        }`
Rather than: 
`        let bundle = Bundle(for: object_getClass(self))
        
        let path: String
        
        if let path1 = bundle.path(forResource: "Notepad.framework/themes/\(name)", ofType: "json") {
            
            path = path1
        }
        else if let path2 = bundle.path(forResource: "Notepad.framework/\(name)", ofType: "json") {
            
            path = path2
        }
        else {
            
            print("[Notepad] Unable to load your theme file.")
            
            return
        }
        
        if let data = convertFile(path) {
            
            configure(data)
        }`

**Comment by ruddfawcett** [comment]
@curtisbacon thanks for this. I am out this week, so you think you can open a PR? I can review and merge in remotely.

**Comment by curtisbacon** [comment]
@ruddfawcett  Sorry for the delay! I believe master is up to date with the changes. You just need to submit a new release
