### ISSUE TITLE
Please add the possibility to change the syntax color and clickable links.

### ISSUE THREAD

**Issue by kaleidscpe** [ruddfawcett/Notepad#43]
It's a very good library and I like it because the themes are customizable. But I've tried everything to change the color of the syntax, but I didn't succeed.

Another problem I found with the links: It's only colored text, but not selectable.

Best regards.

**Comment by ruddfawcett** [comment]
Hi, thanks for the feedback. What do you mean by "[you've] tried everything to change the color of the syntax, but [you] didn't succeed"? Have you looked through the themes included in the project?

Also, Notepad is (right now) just for writing and editing raw text.

**Comment by kaleidscpe** [comment]
I mean the ability to change color to syntax symbols (#, **, ``).

**Comment by ruddfawcett** [comment]
Hi, I don't have time right now to work on this. You are more than welcome to submit a PR, however.

**Comment by ruddfawcett** [comment]
Hi, I'm closing this due to the duplication of #28; right now there are no plans to support clickable links.
