### ISSUE TITLE
macOS pod installation

### ISSUE THREAD

**Issue by kaleidscpe** [ruddfawcett/Notepad#44]
When I try to install Notepad via CocoaPod for my macOS app, I get the following error:
The platform of the target `NameApp` (macOS 10.13) is not compatible with` Notepad (0.2.4) `, which does not support` osx`.

Thanks.

**Comment by ruddfawcett** [comment]
Hi, if you could submit a PR to fix the Podspec, I can merge it in. Thanks!

**Comment by ruddfawcett** [comment]
This should be fixed via the latest CocoaPods update!

**Comment by kaleidscpe** [comment]
Thanks!
