### ISSUE TITLE
Issue with Xcode 10.2

### ISSUE THREAD

**Issue by kaleidscpe** [ruddfawcett/Notepad#46]
I updated Xcode to version 10.2 and from that moment Notepad stopped working. I receive the error "[Notepad] Unable to load your theme file.".

**Comment by ruddfawcett** [comment]
Hi, if you could submit a PR to fix the Podspec, I can merge it in. Thanks!

**Comment by ruddfawcett** [comment]
This should be closed via #48 I think — please reopen if not @kaleidscpe.
