### ISSUE TITLE
Unable to load your theme file.

### ISSUE THREAD

**Issue by GreenSheep0** [ruddfawcett/Notepad#52]
# Hello !
I have added Nodepad to my IOS project but I have this error :
`[Notepad] Unable to load your theme file.`
My code : 
```swift
import UIKit
import Foundation
import Notepad

@IBOutlet weak var textView: UITextView!

override func viewDidLoad() {
        super.viewDidLoad()
            let containerSize = CGSize(width: self.view.bounds.width, height: CGFloat.greatestFiniteMagnitude)
            let container = NSTextContainer(size: containerSize)
            container.widthTracksTextView = true
        
            let layoutManager = NSLayoutManager()
            layoutManager.addTextContainer(container)
        
            let storage = Storage()
            let theme = Theme("one-dark")
            storage.theme = theme
            storage.addLayoutManager(layoutManager)
        
            let editor = UITextView(frame: self.view.bounds, textContainer: container)
            editor.backgroundColor = theme.backgroundColor
            editor.tintColor = theme.tintColor
            editor.autoresizingMask = [.flexibleWidth, .flexibleHeight]
}
```
Thank you in advance

PS : Sorry for my bad English :/

**Comment by ruddfawcett** [comment]
What version of Notepad are you using?

Habitez-vous en France? On peut parler en français si c'est plus facile.

**Comment by PodyDev** [comment]
Merci pour cette réponse.
J'utilise la version `0.3.0`

![Version](https://user-images.githubusercontent.com/40074561/56282661-fab3c580-610f-11e9-9ae6-e4eb2c5d15ae.png)

**Comment by ruddfawcett** [comment]
Bien sur! Avez-vous vu #48?

**Comment by ruddfawcett** [comment]
Peux-tu vérifier que les dossier des «themes» sont choisis?

**Comment by PodyDev** [comment]
Désolé pour cette réponse tardive.

Je ne vois pas de dossier nommé `themes`
![CoolScreen](https://user-images.githubusercontent.com/40074561/56497594-7e99f300-64fe-11e9-8593-6c66407723a4.png)

Je rappelle que j'utilise les CocoaPods pour mon app.

**Comment by ruddfawcett** [comment]
Non, c’est pas problème! Ce soir je vais créer un nouvel projet que utilise CocoaPods. Si j’ai le même problème, je le réparerai.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shusain93** [comment]
I had to make a small patch to make my fresh CocoaPod install work:

Theme.swift:

in `public init(_ name: String)`, add a forth search location:

```
else if let path4 = bundle.path(forResource: name, ofType: "json") {  
            path = path4
}
```

Seems like the build system/cocoapods is copying theme resources to the root of the framework bundle.

**Comment by ruddfawcett** [comment]
Thanks @shusain93 — would you be able to open a PR with this?

**Comment by hstdt** [comment]
This way will be more convenience for swift package manager.

![image](https://user-images.githubusercontent.com/10215098/71239306-2cd19300-2341-11ea-8c82-e29dc622f971.png)

**Comment by ruddfawcett** [comment]
@hstdt / @shusain93 sorry for inactivity on my end. Would it be possible to send in a PR with your patch?

**Comment by ruddfawcett** [comment]
@GreenSheep0 on pense que #57 est la solution au problème.
