### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by mrimadali** [ruddfawcett/Notepad#56]
Hi @ruddfawcett 

Thanks for the awesome library.
Is this library supports Objective-C? I'm integrating using Cocoapods.

Thanks
Imad

**Comment by ruddfawcett** [comment]
Hi, this library was rebuilt for Swift, but was based on [RFMarkdownTextView](https://github.com/ruddfawcett/RFMarkdownTextView). You may want to check that out if you want a pure Objective-C version.

You can also [import Swift into your Objective-C project](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c).
