### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by SolorzanoJose** [ruddfawcett/Notepad#63]
Do we have any insight on how to customize the highlightning for custom attributes? say I want to add something called "user mention" like: [user][username], is this possible? if not out of the box then maybe guide me to the correct classes to implement it myself

**Comment by ruddfawcett** [comment]
Hi @SolorzanoJose, sorry for my delayed response. This is supported! Check out [custom regex](https://github.com/ruddfawcett/Notepad#custom-regex). Feel free to reopen with any other questions.
