### ISSUE TITLE
Cannot call value of non-function type module<Notepad>

### ISSUE THREAD

**Issue by besi** [ruddfawcett/Notepad#7]
I wanted to give Notepad a try so I added the Pod to my project and I could also import it like so:

```swift
import Notepad
```
![import](https://cloud.githubusercontent.com/assets/160412/22251161/1c2f9f32-e24a-11e6-9842-b87f0324706b.png)

### The problem

As soon as I try to instantiate a `Notepad` object I get the following error:

![screen shot 2017-01-24 at 15 28 41](https://cloud.githubusercontent.com/assets/160412/22251091/d718f59c-e249-11e6-9966-018dcdb85f89.png)

I am using the Xcode 8.2.1

**Comment by ruddfawcett** [comment]
Hey, thanks for the report – I'll look into it as soon as I can.

**Comment by ruddfawcett** [comment]
Hey @besi did you ever figure this out? I think it may be an issue with CocoaPods, though I'm not entirely sure...

**Comment by besi** [comment]
Since the demo worked I decided to copy the files over into my project which then worked fine.

**Comment by ruddfawcett** [comment]
Great, thanks for update!
