### ISSUE TITLE
Code regular expression

### ISSUE THREAD

**Issue by MicahTWilson** [ruddfawcett/Notepad#8]
I noticed looking through the example that the "code" regular expression wasn't matching statements like \`let something = "hello"\`

Can I suggest we change your current code expression which is:
```swift
case code = "(`\\w+(\\s\\w+)*`)"
```

to something that allows for any character like:
```swift
case code = "(`.*`)"
```

**Comment by ruddfawcett** [comment]
Definitely! I'm not at a computer for most of this weekend, but if you open a PR I can merge from phone!

**Comment by MicahTWilson** [comment]
Awesome here is the PR: #9
